id: "debian-11"
name: "Debian 11 (Bullseye)"
os_element: "debian"
env:
  DIB_RELEASE: "bullseye"
elements:
  - "vm"
  - "simple-init"
  - "cloud-init"
  - "cloud-init-custom"
  - "openssh-server"
  - "enable-serial-console"
  - "block-device-efi"
  - "bootloader"
  - "journal-to-console"
  - "dhcp-all-interfaces"
  - "agent-install"
  - "cloud-init-datasources"
  - "package-installs"
  - "sysprep"
