id: "ubuntu-24"
name: "Ubuntu 24.04 (Noble)"
os_element: "ubuntu"
env:
  DIB_RELEASE: "noble"
elements:
  - "vm"
  - "simple-init"
  - "cloud-init"
  - "cloud-init-custom"
  - "openssh-server"
  - "enable-serial-console"
  - "block-device-efi"
  - "bootloader"
  - "journal-to-console"
  - "dhcp-all-interfaces"
  - "agent-install"
  - "cloud-init-datasources"
  - "package-installs"
  - "sysprep"
